export const SortTypes = {
    GENERATE_GRAPH: 'GENERATE_GRAPH',
    UPDATE_GRAPH: 'UPDATE_GRAPH',
    TOGGLE_SORT_RUNNING: 'TOGGLE_SORT_RUNNING',
    TOGGLE_STOP_CLICKED: 'TOGGLE_STOP_CLICKED',
    UPDATE_LEFT_POINTER: 'UPDATE_LEFT_POINTER',
    UPDATE_RIGHT_POINTER: 'UPDATE_RIGHT_POINTER'
}

